# Generated by Django 3.2.11 on 2024-12-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_cliente',
        ),
    ]
